openapi: 3.0.0

info:
  title: Muchi Dungeon
  version: 1.0.0

paths:
  /:
    get:
      operationId: api.main.get
      responses:
        '200':
          description: 成功時のレスポンス
          content:
            text/html:
              schema:
                type: string
